### ISSUE TITLE
Name Change for project?

### ISSUE THREAD

**Issue by theaeolianmachine** [kbacha/stellar-rust-sdk#229]
Hello maintainers! I'm Johnny, and I lead developer relations over at Stellar.org.

First, I wanted to say thank you to everyone for all of your great contributions here - it's really great to see such a fully fledged client for Stellar built in Rust, and we're all really excited to see where development goes from here.

Of note, I was wondering if you all would consider changing the name of the project on Github, particularly noting that it's a Rust SDK (such as stellar-rust-sdk). When looking at the rest of our community maintained SDK's, all of them point to the framework or language they are built for, and we feel it will help with differentiating itself from other SDK's, as well as making it easier to find an SDK for Rust.

I haven't spoken to other community members regarding the other Rust SDK's, so if there's any precedent for not putting Rust in the name of the project, I'm all ears.

Finally, there's no issue with the library being called stellar_client or something without Rust in the name, as that's implied when coding in the language - we're just thinking about the name on Github.

Let me know what your thoughts are, and thanks!

**Comment by kbacha** [comment]
Yea, I can work to migrate the name. It might break existing links and what-not (especially those on crates.io) but it's not required for anything.
